# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        stages: [pre-commit, pre-push]
      - id: check-json
        stages: [pre-commit, pre-push]
      - id: end-of-file-fixer
        stages: [pre-commit, pre-push]
      - id: trailing-whitespace
        stages: [pre-commit, pre-push]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --profile black
        language: system
        types: [python]
        stages: [pre-commit, pre-push]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        stages: [pre-commit, pre-push]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        stages: [pre-commit, pre-push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
        language: system
        types: [python]
        args: ["--config-file=mypy.ini"]
        stages: [pre-commit, pre-push]
