snow_wh:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dev-cloud-warehouse
      dataset: dbt_base
      threads: 4
      timeout_seconds: 300
      location: us-central1
