snow_wh:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "QMUGLJO-NE36888"
      user: "AARONSIME"
      password: "{{ env_var('SNOWFLAKE_PASSWORD_RUN') }}"
      role: "DBT_ROLE"
      database: "DEV_CLOUD_DATAWAREHOUSE"
      warehouse: "COMPUTE_WH"
      schema: DBT_BASE
