schedules:
  daily:
    - name: ingestion # this is the job folder in /jobs folder
      run_job_name: cloud-scheduler-cloudrun-job-ingestion # this is the cloud run job name
      region: us-central1 # this is the same region with the cloud run job
