name: "t-Run linters for Python"

on: push

jobs:
  run-linters:
    name: Run linters for Python
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run static type checks with pre-commit
        run: pre-commit run --hook-stage manual -a

      - name: Run isort
        run: isort --check-only --profile black .

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          black: true
          flake8: true
          mypy: true
